// このファイルは生成物。手で書き換えない。
// 元は translations/core.json、作るのは ./Tools-GenCore.py（引き継ぎ書 4-158）

extension Preset {
    /// その言語の雛形。言語ごとに関数を分けてある（大きな辞書のリテラルは型の推論が遅い）。
    static func table(_ language: Language) -> [Preset] {
        switch language {
        case .ja: return ja()
        case .en: return en()
        case .zhHans: return zhHans()
        case .zhHant: return zhHant()
        case .ko: return ko()
        case .es: return es()
        case .fr: return fr()
        case .de: return de()
        case .it: return it()
        case .ptBR: return ptBR()
        case .ru: return ru()
        case .ar: return ar()
        }
    }

    private static func ja() -> [Preset] {
        [
            Preset(id: "town", name: "街中", detail: "ちょっと外出するとき",
                   palette: Palette(1), columns: .four,
                   text: "財布\nスマホ\n鍵\nハンカチ\n\nイヤホン\n充電器\nモバイル充電\n\n目薬\nリップ\nマスク"),
            Preset(id: "commute", name: "通勤・通学", detail: "毎日のかばんの中身",
                   palette: Palette(2), columns: .four,
                   text: "財布\nスマホ\n鍵\n社員証\n\n定期券\nICカード\n\nノートPC\n充電器\n手帳\nペン\n\n弁当\n水筒\n折りたたみ傘"),
            Preset(id: "trip-domestic", name: "国内旅行", detail: "1〜2泊のふつうの旅行",
                   palette: Palette(3), columns: .four,
                   text: "財布\nスマホ\n鍵\n免許証\n\n着替え\n下着\n靴下\nパジャマ\n\n歯ブラシ\n洗顔\n化粧品\nタオル\n\n充電器\nモバイル充電\nイヤホン\n\n常備薬\n絆創膏\nマスク\n\nエコバッグ\nビニール袋"),
            Preset(id: "trip-abroad", name: "海外旅行", detail: "現地で買えないものを先に",
                   palette: Palette(4), columns: .four,
                   text: "パスポート\n航空券\n財布\n現金\n\nクレカ\n保険証書\neSIM\n\n変換プラグ\n充電器\nモバイル充電\n\n着替え\n下着\n靴下\n上着\n\n歯ブラシ\n洗面用具\n化粧品\n\n常備薬\n酔い止め\nマスク\n\nアイマスク\n耳栓\nネックピロー"),
            Preset(id: "business", name: "出張", detail: "1泊の仕事の遠出",
                   palette: Palette(5), columns: .four,
                   text: "財布\nスマホ\n社員証\n名刺\n\nノートPC\n充電器\nマウス\n\n資料\n手帳\nペン\n\n着替え\n下着\nワイシャツ\n\n歯ブラシ\n洗面用具\n\n常備薬\n折りたたみ傘"),
            Preset(id: "gym", name: "ジム・運動", detail: "運動しに行くとき",
                   palette: Palette(6), columns: .four,
                   text: "ウェア\n短パン\n靴下\n\nシューズ\nタオル\n着替え\n\n水筒\nプロテイン\n\n会員証\nロッカー鍵\n\nシャンプー\nボディソープ"),
            Preset(id: "camp", name: "キャンプ・BBQ", detail: "外で火を使うとき",
                   palette: Palette(7), columns: .four,
                   text: "テント\nペグ\nハンマー\n\n寝袋\nマット\nランタン\n\nコンロ\n炭\n着火剤\nトング\n\nクーラー\n食材\n飲み物\n\n食器\n箸\n調味料\n\n軍手\nゴミ袋\n虫除け"),
            Preset(id: "onsen", name: "温泉・銭湯", detail: "お風呂に行くとき",
                   palette: Palette(8), columns: .four,
                   text: "タオル\nバスタオル\n着替え\n\n下着\n靴下\n\nシャンプー\n洗顔\n化粧水\n\n髪ゴム\n小銭\n飲み物"),
            Preset(id: "kids", name: "子どもとおでかけ", detail: "小さい子を連れて出るとき",
                   palette: Palette(9), columns: .four,
                   text: "おむつ\nおしりふき\nビニール袋\n\n着替え\nスタイ\nタオル\n\nミルク\n哺乳瓶\n麦茶\n\nおやつ\nおもちゃ\n絵本\n\n母子手帳\n保険証\n診察券\n\n抱っこ紐\n日焼け止め\n帽子"),
            Preset(id: "hospital", name: "通院", detail: "病院へ行くとき",
                   palette: Palette(10), columns: .four,
                   text: "保険証\n診察券\nお薬手帳\n\n財布\n現金\nスマホ\n\n紹介状\n検査結果\n\nマスク\n飲み物"),
            Preset(id: "ceremony", name: "冠婚葬祭", detail: "急に必要になるもの",
                   palette: Palette(4), columns: .four,
                   text: "礼服\nネクタイ\n黒靴下\n\n袱紗\n香典\nご祝儀袋\n\n数珠\nハンカチ\n筆ペン\n\n財布\nスマホ"),
            Preset(id: "disaster", name: "防災", detail: "持ち出し袋の中身",
                   palette: Palette(8), columns: .four,
                   text: "水\n非常食\n携帯ラジオ\n\n懐中電灯\n電池\nモバイル充電\n\n救急セット\n常備薬\nマスク\n\n現金\n身分証コピー\n通帳\n\n軍手\nホイッスル\nレインコート\n\nタオル\n歯ブラシ\n携帯トイレ"),
        ]
    }

    private static func en() -> [Preset] {
        [
            Preset(id: "town", name: "Going out", detail: "A quick trip out",
                   palette: Palette(1), columns: .four,
                   text: "Wallet\nPhone\nKeys\nTissues\n\nEarbuds\nCharger\nPower bank\n\nEye drops\nLip balm\nMask"),
            Preset(id: "commute", name: "Commute", detail: "Your everyday bag",
                   palette: Palette(2), columns: .four,
                   text: "Wallet\nPhone\nKeys\nWork ID\n\nTransit pass\nMetro card\n\nLaptop\nCharger\nPlanner\nPen\n\nLunch\nWater bottle\nUmbrella"),
            Preset(id: "trip-domestic", name: "Weekend trip", detail: "One or two nights away",
                   palette: Palette(3), columns: .four,
                   text: "Wallet\nPhone\nKeys\nDriver's license\n\nClothes\nUnderwear\nSocks\nPajamas\n\nToothbrush\nFace wash\nMakeup\nTowel\n\nCharger\nPower bank\nEarbuds\n\nMedicine\nBand-aids\nMask\n\nTote bag\nPlastic bags"),
            Preset(id: "trip-abroad", name: "Trip abroad", detail: "Things you can't buy there",
                   palette: Palette(4), columns: .four,
                   text: "Passport\nTickets\nWallet\nCash\n\nCredit card\nInsurance\neSIM\n\nPlug adapter\nCharger\nPower bank\n\nClothes\nUnderwear\nSocks\nJacket\n\nToothbrush\nToiletries\nMakeup\n\nMedicine\nNausea pills\nMask\n\nEye mask\nEarplugs\nNeck pillow"),
            Preset(id: "business", name: "Business trip", detail: "One night away for work",
                   palette: Palette(5), columns: .four,
                   text: "Wallet\nPhone\nWork ID\nBusiness cards\n\nLaptop\nCharger\nMouse\n\nDocuments\nPlanner\nPen\n\nClothes\nUnderwear\nDress shirt\n\nToothbrush\nToiletries\n\nMedicine\nUmbrella"),
            Preset(id: "gym", name: "Gym", detail: "Heading out to work out",
                   palette: Palette(6), columns: .four,
                   text: "Workout top\nShorts\nSocks\n\nShoes\nTowel\nSpare clothes\n\nWater bottle\nProtein\n\nMember card\nLocker key\n\nShampoo\nBody wash"),
            Preset(id: "camp", name: "Camping & BBQ", detail: "Cooking outdoors",
                   palette: Palette(7), columns: .four,
                   text: "Tent\nPegs\nMallet\n\nSleeping bag\nMat\nLantern\n\nStove\nCharcoal\nFire starter\nTongs\n\nCooler\nFood\nDrinks\n\nDishes\nUtensils\nSeasonings\n\nWork gloves\nTrash bags\nBug spray"),
            Preset(id: "onsen", name: "Bathhouse", detail: "Going for a soak",
                   palette: Palette(8), columns: .four,
                   text: "Towel\nBath towel\nSpare clothes\n\nUnderwear\nSocks\n\nShampoo\nFace wash\nToner\n\nHair tie\nCoins\nDrink"),
            Preset(id: "kids", name: "Out with kids", detail: "Taking little ones along",
                   palette: Palette(9), columns: .four,
                   text: "Diapers\nWipes\nPlastic bags\n\nSpare clothes\nBib\nTowel\n\nFormula\nBottle\nWater\n\nSnacks\nToys\nPicture book\n\nHealth record\nInsurance card\nClinic card\n\nBaby carrier\nSunscreen\nHat"),
            Preset(id: "hospital", name: "Doctor visit", detail: "Going to the clinic",
                   palette: Palette(10), columns: .four,
                   text: "Insurance card\nClinic card\nMed list\n\nWallet\nCash\nPhone\n\nReferral\nTest results\n\nMask\nDrink"),
            Preset(id: "ceremony", name: "Formal event", detail: "Weddings and funerals",
                   palette: Palette(4), columns: .four,
                   text: "Formal wear\nTie\nBlack socks\n\nGift\nCard\nEnvelope\n\nHandkerchief\nPen\nMints\n\nWallet\nPhone"),
            Preset(id: "disaster", name: "Emergency kit", detail: "What goes in the go-bag",
                   palette: Palette(8), columns: .four,
                   text: "Water\nEmergency food\nRadio\n\nFlashlight\nBatteries\nPower bank\n\nFirst aid kit\nMedicine\nMask\n\nCash\nCopy of ID\nBank card\n\nWork gloves\nWhistle\nRaincoat\n\nTowel\nToothbrush\nToilet bags"),
        ]
    }

    private static func zhHans() -> [Preset] {
        [
            Preset(id: "town", name: "日常外出", detail: "出门办点事",
                   palette: Palette(1), columns: .four,
                   text: "钱包\n手机\n钥匙\n纸巾\n\n耳机\n充电器\n充电宝\n\n眼药水\n润唇膏\n口罩"),
            Preset(id: "commute", name: "通勤上学", detail: "每天的包里",
                   palette: Palette(2), columns: .four,
                   text: "钱包\n手机\n钥匙\n工牌\n\n月票\n交通卡\n\n笔记本电脑\n充电器\n记事本\n笔\n\n便当\n水杯\n折叠伞"),
            Preset(id: "trip-domestic", name: "短途旅行", detail: "住一两晚的旅行",
                   palette: Palette(3), columns: .four,
                   text: "钱包\n手机\n钥匙\n驾照\n\n换洗衣物\n内衣\n袜子\n睡衣\n\n牙刷\n洗面奶\n化妆品\n毛巾\n\n充电器\n充电宝\n耳机\n\n常备药\n创可贴\n口罩\n\n环保袋\n塑料袋"),
            Preset(id: "trip-abroad", name: "出国旅行", detail: "当地买不到的先带上",
                   palette: Palette(4), columns: .four,
                   text: "护照\n机票\n钱包\n现金\n\n信用卡\n保险单\neSIM\n\n转换插头\n充电器\n充电宝\n\n换洗衣物\n内衣\n袜子\n外套\n\n牙刷\n洗漱用品\n化妆品\n\n常备药\n晕车药\n口罩\n\n眼罩\n耳塞\n颈枕"),
            Preset(id: "business", name: "出差", detail: "一晚的工作出行",
                   palette: Palette(5), columns: .four,
                   text: "钱包\n手机\n工牌\n名片\n\n笔记本电脑\n充电器\n鼠标\n\n资料\n记事本\n笔\n\n换洗衣物\n内衣\n衬衫\n\n牙刷\n洗漱用品\n\n常备药\n折叠伞"),
            Preset(id: "gym", name: "健身运动", detail: "去运动的时候",
                   palette: Palette(6), columns: .four,
                   text: "运动服\n短裤\n袜子\n\n运动鞋\n毛巾\n换洗衣物\n\n水杯\n蛋白粉\n\n会员卡\n柜子钥匙\n\n洗发水\n沐浴露"),
            Preset(id: "camp", name: "露营烧烤", detail: "在户外生火做饭",
                   palette: Palette(7), columns: .four,
                   text: "帐篷\n地钉\n锤子\n\n睡袋\n防潮垫\n营灯\n\n炉子\n木炭\n引火剂\n夹子\n\n保温箱\n食材\n饮料\n\n餐具\n筷子\n调料\n\n手套\n垃圾袋\n驱蚊液"),
            Preset(id: "onsen", name: "温泉澡堂", detail: "去泡澡的时候",
                   palette: Palette(8), columns: .four,
                   text: "毛巾\n浴巾\n换洗衣物\n\n内衣\n袜子\n\n洗发水\n洗面奶\n爽肤水\n\n发圈\n零钱\n饮料"),
            Preset(id: "kids", name: "带娃出门", detail: "带小孩出去时",
                   palette: Palette(9), columns: .four,
                   text: "尿布\n湿巾\n塑料袋\n\n换洗衣物\n围兜\n毛巾\n\n奶粉\n奶瓶\n温水\n\n零食\n玩具\n绘本\n\n母婴手册\n医保卡\n就诊卡\n\n背带\n防晒霜\n帽子"),
            Preset(id: "hospital", name: "看病", detail: "去医院的时候",
                   palette: Palette(10), columns: .four,
                   text: "医保卡\n就诊卡\n用药记录\n\n钱包\n现金\n手机\n\n转诊单\n检查结果\n\n口罩\n饮料"),
            Preset(id: "ceremony", name: "红白喜事", detail: "临时要用的东西",
                   palette: Palette(4), columns: .four,
                   text: "正装\n领带\n黑袜子\n\n礼金\n贺卡\n红包\n\n手帕\n笔\n口香糖\n\n钱包\n手机"),
            Preset(id: "disaster", name: "应急包", detail: "避难时带走的东西",
                   palette: Palette(8), columns: .four,
                   text: "饮用水\n应急食品\n收音机\n\n手电筒\n电池\n充电宝\n\n急救包\n常备药\n口罩\n\n现金\n证件复印件\n银行卡\n\n手套\n哨子\n雨衣\n\n毛巾\n牙刷\n便携厕所"),
        ]
    }

    private static func zhHant() -> [Preset] {
        [
            Preset(id: "town", name: "日常外出", detail: "出門辦點事",
                   palette: Palette(1), columns: .four,
                   text: "錢包\n手機\n鑰匙\n面紙\n\n耳機\n充電器\n行動電源\n\n眼藥水\n護唇膏\n口罩"),
            Preset(id: "commute", name: "通勤上學", detail: "每天的包包裡",
                   palette: Palette(2), columns: .four,
                   text: "錢包\n手機\n鑰匙\n識別證\n\n月票\n交通卡\n\n筆電\n充電器\n手帳\n筆\n\n便當\n水壺\n折疊傘"),
            Preset(id: "trip-domestic", name: "短程旅行", detail: "住一兩晚的旅行",
                   palette: Palette(3), columns: .four,
                   text: "錢包\n手機\n鑰匙\n駕照\n\n換洗衣物\n內衣\n襪子\n睡衣\n\n牙刷\n洗面乳\n化妝品\n毛巾\n\n充電器\n行動電源\n耳機\n\n常備藥\nOK繃\n口罩\n\n環保袋\n塑膠袋"),
            Preset(id: "trip-abroad", name: "出國旅行", detail: "當地買不到的先帶",
                   palette: Palette(4), columns: .four,
                   text: "護照\n機票\n錢包\n現金\n\n信用卡\n保險單\neSIM\n\n轉接插頭\n充電器\n行動電源\n\n換洗衣物\n內衣\n襪子\n外套\n\n牙刷\n盥洗用品\n化妝品\n\n常備藥\n暈車藥\n口罩\n\n眼罩\n耳塞\n頸枕"),
            Preset(id: "business", name: "出差", detail: "一晚的工作行程",
                   palette: Palette(5), columns: .four,
                   text: "錢包\n手機\n識別證\n名片\n\n筆電\n充電器\n滑鼠\n\n資料\n手帳\n筆\n\n換洗衣物\n內衣\n襯衫\n\n牙刷\n盥洗用品\n\n常備藥\n折疊傘"),
            Preset(id: "gym", name: "健身運動", detail: "去運動的時候",
                   palette: Palette(6), columns: .four,
                   text: "運動服\n短褲\n襪子\n\n運動鞋\n毛巾\n換洗衣物\n\n水壺\n高蛋白\n\n會員卡\n置物櫃鑰匙\n\n洗髮精\n沐浴乳"),
            Preset(id: "camp", name: "露營烤肉", detail: "在戶外生火的時候",
                   palette: Palette(7), columns: .four,
                   text: "帳篷\n營釘\n槌子\n\n睡袋\n睡墊\n營燈\n\n爐具\n木炭\n助燃劑\n夾子\n\n冰桶\n食材\n飲料\n\n餐具\n筷子\n調味料\n\n手套\n垃圾袋\n防蚊液"),
            Preset(id: "onsen", name: "溫泉澡堂", detail: "去泡湯的時候",
                   palette: Palette(8), columns: .four,
                   text: "毛巾\n浴巾\n換洗衣物\n\n內衣\n襪子\n\n洗髮精\n洗面乳\n化妝水\n\n髮圈\n零錢\n飲料"),
            Preset(id: "kids", name: "帶小孩出門", detail: "帶小小孩出去時",
                   palette: Palette(9), columns: .four,
                   text: "尿布\n濕紙巾\n塑膠袋\n\n換洗衣物\n圍兜\n毛巾\n\n奶粉\n奶瓶\n溫水\n\n零食\n玩具\n繪本\n\n兒童手冊\n健保卡\n掛號證\n\n揹帶\n防曬乳\n帽子"),
            Preset(id: "hospital", name: "看醫生", detail: "去醫院的時候",
                   palette: Palette(10), columns: .four,
                   text: "健保卡\n掛號證\n用藥紀錄\n\n錢包\n現金\n手機\n\n轉診單\n檢查報告\n\n口罩\n飲料"),
            Preset(id: "ceremony", name: "婚喪喜慶", detail: "臨時需要的東西",
                   palette: Palette(4), columns: .four,
                   text: "正式服裝\n領帶\n黑襪子\n\n禮金\n卡片\n紅包袋\n\n手帕\n筆\n口香糖\n\n錢包\n手機"),
            Preset(id: "disaster", name: "防災包", detail: "避難時帶走的東西",
                   palette: Palette(8), columns: .four,
                   text: "飲用水\n緊急糧食\n收音機\n\n手電筒\n電池\n行動電源\n\n急救包\n常備藥\n口罩\n\n現金\n證件影本\n存摺\n\n手套\n哨子\n雨衣\n\n毛巾\n牙刷\n攜帶式馬桶"),
        ]
    }

    private static func ko() -> [Preset] {
        [
            Preset(id: "town", name: "외출", detail: "잠깐 나갈 때",
                   palette: Palette(1), columns: .four,
                   text: "지갑\n휴대폰\n열쇠\n손수건\n\n이어폰\n충전기\n보조배터리\n\n안약\n립밤\n마스크"),
            Preset(id: "commute", name: "출근·등교", detail: "매일 챙기는 가방",
                   palette: Palette(2), columns: .four,
                   text: "지갑\n휴대폰\n열쇠\n사원증\n\n정기권\n교통카드\n\n노트북\n충전기\n수첩\n펜\n\n도시락\n텀블러\n접이식 우산"),
            Preset(id: "trip-domestic", name: "국내 여행", detail: "1~2박 여행",
                   palette: Palette(3), columns: .four,
                   text: "지갑\n휴대폰\n열쇠\n운전면허증\n\n갈아입을 옷\n속옷\n양말\n잠옷\n\n칫솔\n폼클렌징\n화장품\n수건\n\n충전기\n보조배터리\n이어폰\n\n상비약\n반창고\n마스크\n\n에코백\n비닐봉지"),
            Preset(id: "trip-abroad", name: "해외여행", detail: "현지에서 못 사는 것부터",
                   palette: Palette(4), columns: .four,
                   text: "여권\n항공권\n지갑\n현금\n\n신용카드\n여행자보험\neSIM\n\n변환 플러그\n충전기\n보조배터리\n\n갈아입을 옷\n속옷\n양말\n겉옷\n\n칫솔\n세면도구\n화장품\n\n상비약\n멀미약\n마스크\n\n안대\n귀마개\n목베개"),
            Preset(id: "business", name: "출장", detail: "1박 업무 출장",
                   palette: Palette(5), columns: .four,
                   text: "지갑\n휴대폰\n사원증\n명함\n\n노트북\n충전기\n마우스\n\n자료\n수첩\n펜\n\n갈아입을 옷\n속옷\n와이셔츠\n\n칫솔\n세면도구\n\n상비약\n접이식 우산"),
            Preset(id: "gym", name: "헬스·운동", detail: "운동하러 갈 때",
                   palette: Palette(6), columns: .four,
                   text: "운동복\n반바지\n양말\n\n운동화\n수건\n갈아입을 옷\n\n텀블러\n프로틴\n\n회원카드\n사물함 열쇠\n\n샴푸\n바디워시"),
            Preset(id: "camp", name: "캠핑·바비큐", detail: "밖에서 불을 쓸 때",
                   palette: Palette(7), columns: .four,
                   text: "텐트\n팩\n망치\n\n침낭\n매트\n랜턴\n\n버너\n숯\n착화제\n집게\n\n아이스박스\n식재료\n음료\n\n식기\n젓가락\n양념\n\n목장갑\n쓰레기봉투\n모기 기피제"),
            Preset(id: "onsen", name: "온천·목욕탕", detail: "목욕하러 갈 때",
                   palette: Palette(8), columns: .four,
                   text: "수건\n목욕 타월\n갈아입을 옷\n\n속옷\n양말\n\n샴푸\n폼클렌징\n스킨\n\n머리끈\n동전\n음료"),
            Preset(id: "kids", name: "아이와 외출", detail: "어린아이와 나갈 때",
                   palette: Palette(9), columns: .four,
                   text: "기저귀\n물티슈\n비닐봉지\n\n갈아입을 옷\n턱받이\n수건\n\n분유\n젖병\n보리차\n\n간식\n장난감\n그림책\n\n아기수첩\n건강보험증\n진찰권\n\n아기띠\n선크림\n모자"),
            Preset(id: "hospital", name: "병원", detail: "병원에 갈 때",
                   palette: Palette(10), columns: .four,
                   text: "건강보험증\n진찰권\n약 수첩\n\n지갑\n현금\n휴대폰\n\n진료의뢰서\n검사 결과\n\n마스크\n음료"),
            Preset(id: "ceremony", name: "경조사", detail: "갑자기 필요한 것",
                   palette: Palette(4), columns: .four,
                   text: "정장\n넥타이\n검은 양말\n\n축의금\n카드\n봉투\n\n손수건\n펜\n껌\n\n지갑\n휴대폰"),
            Preset(id: "disaster", name: "비상용품", detail: "비상 가방 속 물건",
                   palette: Palette(8), columns: .four,
                   text: "물\n비상식량\n휴대용 라디오\n\n손전등\n건전지\n보조배터리\n\n구급상자\n상비약\n마스크\n\n현금\n신분증 사본\n통장\n\n목장갑\n호루라기\n우비\n\n수건\n칫솔\n휴대용 변기"),
        ]
    }

    private static func es() -> [Preset] {
        [
            Preset(id: "town", name: "Salir", detail: "Una salida rápida",
                   palette: Palette(1), columns: .four,
                   text: "Cartera\nMóvil\nLlaves\nPañuelos\n\nAuriculares\nCargador\nBatería externa\n\nColirio\nBálsamo labial\nMascarilla"),
            Preset(id: "commute", name: "Al trabajo", detail: "Tu bolso de cada día",
                   palette: Palette(2), columns: .four,
                   text: "Cartera\nMóvil\nLlaves\nCredencial\n\nAbono\nTarjeta de metro\n\nPortátil\nCargador\nAgenda\nBolígrafo\n\nAlmuerzo\nBotella de agua\nParaguas"),
            Preset(id: "trip-domestic", name: "Escapada", detail: "Una o dos noches fuera",
                   palette: Palette(3), columns: .four,
                   text: "Cartera\nMóvil\nLlaves\nCarné de conducir\n\nRopa\nRopa interior\nCalcetines\nPijama\n\nCepillo de dientes\nLimpiador facial\nMaquillaje\nToalla\n\nCargador\nBatería externa\nAuriculares\n\nMedicinas\nTiritas\nMascarilla\n\nBolsa de tela\nBolsas de plástico"),
            Preset(id: "trip-abroad", name: "Viaje al extranjero", detail: "Lo que no podrás comprar allí",
                   palette: Palette(4), columns: .four,
                   text: "Pasaporte\nBilletes\nCartera\nEfectivo\n\nTarjeta de crédito\nSeguro\neSIM\n\nAdaptador\nCargador\nBatería externa\n\nRopa\nRopa interior\nCalcetines\nChaqueta\n\nCepillo de dientes\nNeceser\nMaquillaje\n\nMedicinas\nAntimareo\nMascarilla\n\nAntifaz\nTapones\nAlmohada cuello"),
            Preset(id: "business", name: "Viaje de trabajo", detail: "Una noche por trabajo",
                   palette: Palette(5), columns: .four,
                   text: "Cartera\nMóvil\nCredencial\nTarjetas de visita\n\nPortátil\nCargador\nRatón\n\nDocumentos\nAgenda\nBolígrafo\n\nRopa\nRopa interior\nCamisa\n\nCepillo de dientes\nNeceser\n\nMedicinas\nParaguas"),
            Preset(id: "gym", name: "Gimnasio", detail: "Para ir a entrenar",
                   palette: Palette(6), columns: .four,
                   text: "Camiseta\nPantalón corto\nCalcetines\n\nZapatillas\nToalla\nMuda de ropa\n\nBotella de agua\nProteína\n\nTarjeta de socio\nLlave taquilla\n\nChampú\nGel de ducha"),
            Preset(id: "camp", name: "Camping y barbacoa", detail: "Cocinar al aire libre",
                   palette: Palette(7), columns: .four,
                   text: "Tienda\nPiquetas\nMartillo\n\nSaco de dormir\nEsterilla\nFarol\n\nHornillo\nCarbón\nPastillas fuego\nPinzas\n\nNevera\nComida\nBebidas\n\nPlatos\nCubiertos\nCondimentos\n\nGuantes\nBolsas de basura\nRepelente"),
            Preset(id: "onsen", name: "Baños termales", detail: "Para ir a darse un baño",
                   palette: Palette(8), columns: .four,
                   text: "Toalla\nToalla de baño\nMuda de ropa\n\nRopa interior\nCalcetines\n\nChampú\nLimpiador facial\nTónico\n\nColetero\nMonedas\nBebida"),
            Preset(id: "kids", name: "Salir con niños", detail: "Con los más pequeños",
                   palette: Palette(9), columns: .four,
                   text: "Pañales\nToallitas\nBolsas de plástico\n\nMuda de ropa\nBabero\nToalla\n\nLeche en polvo\nBiberón\nAgua\n\nMerienda\nJuguetes\nCuento\n\nCartilla de salud\nTarjeta sanitaria\nTarjeta clínica\n\nPortabebés\nProtector solar\nGorro"),
            Preset(id: "hospital", name: "Al médico", detail: "Para ir a la consulta",
                   palette: Palette(10), columns: .four,
                   text: "Tarjeta sanitaria\nTarjeta clínica\nMedicación\n\nCartera\nEfectivo\nMóvil\n\nVolante\nResultados\n\nMascarilla\nBebida"),
            Preset(id: "ceremony", name: "Evento formal", detail: "Bodas y funerales",
                   palette: Palette(4), columns: .four,
                   text: "Traje\nCorbata\nCalcetines negros\n\nRegalo\nTarjeta\nSobre\n\nPañuelo\nBolígrafo\nCaramelos\n\nCartera\nMóvil"),
            Preset(id: "disaster", name: "Kit de emergencia", detail: "Lo que va en la mochila",
                   palette: Palette(8), columns: .four,
                   text: "Agua\nVíveres\nRadio\n\nLinterna\nPilas\nBatería externa\n\nBotiquín\nMedicinas\nMascarilla\n\nEfectivo\nCopia del DNI\nTarjeta bancaria\n\nGuantes\nSilbato\nChubasquero\n\nToalla\nCepillo de dientes\nBolsas WC"),
        ]
    }

    private static func fr() -> [Preset] {
        [
            Preset(id: "town", name: "Sortir", detail: "Une petite sortie",
                   palette: Palette(1), columns: .four,
                   text: "Portefeuille\nTéléphone\nClés\nMouchoirs\n\nÉcouteurs\nChargeur\nBatterie externe\n\nCollyre\nBaume à lèvres\nMasque"),
            Preset(id: "commute", name: "Trajet quotidien", detail: "Votre sac de tous les jours",
                   palette: Palette(2), columns: .four,
                   text: "Portefeuille\nTéléphone\nClés\nBadge\n\nAbonnement\nCarte de transport\n\nOrdinateur\nChargeur\nAgenda\nStylo\n\nDéjeuner\nGourde\nParapluie"),
            Preset(id: "trip-domestic", name: "Week-end", detail: "Une ou deux nuits",
                   palette: Palette(3), columns: .four,
                   text: "Portefeuille\nTéléphone\nClés\nPermis\n\nVêtements\nSous-vêtements\nChaussettes\nPyjama\n\nBrosse à dents\nNettoyant visage\nMaquillage\nServiette\n\nChargeur\nBatterie externe\nÉcouteurs\n\nMédicaments\nPansements\nMasque\n\nTote bag\nSacs plastique"),
            Preset(id: "trip-abroad", name: "Voyage à l'étranger", detail: "Ce qu'on ne trouve pas là-bas",
                   palette: Palette(4), columns: .four,
                   text: "Passeport\nBillets\nPortefeuille\nEspèces\n\nCarte bancaire\nAssurance\neSIM\n\nAdaptateur\nChargeur\nBatterie externe\n\nVêtements\nSous-vêtements\nChaussettes\nVeste\n\nBrosse à dents\nTrousse toilette\nMaquillage\n\nMédicaments\nAnti-nausée\nMasque\n\nMasque de nuit\nBouchons oreilles\nCoussin de cou"),
            Preset(id: "business", name: "Déplacement pro", detail: "Une nuit pour le travail",
                   palette: Palette(5), columns: .four,
                   text: "Portefeuille\nTéléphone\nBadge\nCartes de visite\n\nOrdinateur\nChargeur\nSouris\n\nDocuments\nAgenda\nStylo\n\nVêtements\nSous-vêtements\nChemise\n\nBrosse à dents\nTrousse toilette\n\nMédicaments\nParapluie"),
            Preset(id: "gym", name: "Salle de sport", detail: "Pour aller s'entraîner",
                   palette: Palette(6), columns: .four,
                   text: "Tenue de sport\nShort\nChaussettes\n\nBaskets\nServiette\nRechange\n\nGourde\nProtéines\n\nCarte membre\nClé casier\n\nShampooing\nGel douche"),
            Preset(id: "camp", name: "Camping et barbecue", detail: "Cuisiner en plein air",
                   palette: Palette(7), columns: .four,
                   text: "Tente\nSardines\nMaillet\n\nSac de couchage\nTapis\nLanterne\n\nRéchaud\nCharbon\nAllume-feu\nPinces\n\nGlacière\nNourriture\nBoissons\n\nVaisselle\nCouverts\nCondiments\n\nGants\nSacs poubelle\nAnti-moustique"),
            Preset(id: "onsen", name: "Bains publics", detail: "Pour aller se baigner",
                   palette: Palette(8), columns: .four,
                   text: "Serviette\nDrap de bain\nRechange\n\nSous-vêtements\nChaussettes\n\nShampooing\nNettoyant visage\nLotion tonique\n\nÉlastique\nMonnaie\nBoisson"),
            Preset(id: "kids", name: "Sortie avec enfants", detail: "Avec les tout-petits",
                   palette: Palette(9), columns: .four,
                   text: "Couches\nLingettes\nSacs plastique\n\nRechange\nBavoir\nServiette\n\nLait en poudre\nBiberon\nEau\n\nGoûter\nJouets\nLivre d'images\n\nCarnet de santé\nCarte vitale\nCarte clinique\n\nPorte-bébé\nCrème solaire\nChapeau"),
            Preset(id: "hospital", name: "Rendez-vous médical", detail: "Pour aller chez le médecin",
                   palette: Palette(10), columns: .four,
                   text: "Carte vitale\nCarte clinique\nOrdonnance\n\nPortefeuille\nEspèces\nTéléphone\n\nLettre du médecin\nRésultats\n\nMasque\nBoisson"),
            Preset(id: "ceremony", name: "Cérémonie", detail: "Mariages et funérailles",
                   palette: Palette(4), columns: .four,
                   text: "Costume\nCravate\nChaussettes noires\n\nCadeau\nCarte\nEnveloppe\n\nMouchoir\nStylo\nBonbons\n\nPortefeuille\nTéléphone"),
            Preset(id: "disaster", name: "Kit d'urgence", detail: "Le contenu du sac d'évacuation",
                   palette: Palette(8), columns: .four,
                   text: "Eau\nRations\nRadio\n\nLampe torche\nPiles\nBatterie externe\n\nTrousse de secours\nMédicaments\nMasque\n\nEspèces\nCopie d'identité\nCarte bancaire\n\nGants\nSifflet\nImperméable\n\nServiette\nBrosse à dents\nWC portable"),
        ]
    }

    private static func de() -> [Preset] {
        [
            Preset(id: "town", name: "Unterwegs", detail: "Kurz mal raus",
                   palette: Palette(1), columns: .four,
                   text: "Geldbörse\nHandy\nSchlüssel\nTaschentücher\n\nKopfhörer\nLadegerät\nPowerbank\n\nAugentropfen\nLippenbalsam\nMaske"),
            Preset(id: "commute", name: "Pendeln", detail: "Deine tägliche Tasche",
                   palette: Palette(2), columns: .four,
                   text: "Geldbörse\nHandy\nSchlüssel\nDienstausweis\n\nMonatskarte\nFahrkarte\n\nLaptop\nLadegerät\nKalender\nStift\n\nMittagessen\nTrinkflasche\nRegenschirm"),
            Preset(id: "trip-domestic", name: "Kurzurlaub", detail: "Ein, zwei Nächte weg",
                   palette: Palette(3), columns: .four,
                   text: "Geldbörse\nHandy\nSchlüssel\nFührerschein\n\nKleidung\nUnterwäsche\nSocken\nSchlafanzug\n\nZahnbürste\nGesichtsreiniger\nMake-up\nHandtuch\n\nLadegerät\nPowerbank\nKopfhörer\n\nMedikamente\nPflaster\nMaske\n\nStoffbeutel\nPlastiktüten"),
            Preset(id: "trip-abroad", name: "Auslandsreise", detail: "Was es dort nicht gibt",
                   palette: Palette(4), columns: .four,
                   text: "Reisepass\nTickets\nGeldbörse\nBargeld\n\nKreditkarte\nVersicherung\neSIM\n\nReiseadapter\nLadegerät\nPowerbank\n\nKleidung\nUnterwäsche\nSocken\nJacke\n\nZahnbürste\nKulturbeutel\nMake-up\n\nMedikamente\nReisetabletten\nMaske\n\nSchlafmaske\nOhrstöpsel\nNackenkissen"),
            Preset(id: "business", name: "Geschäftsreise", detail: "Eine Nacht beruflich",
                   palette: Palette(5), columns: .four,
                   text: "Geldbörse\nHandy\nDienstausweis\nVisitenkarten\n\nLaptop\nLadegerät\nMaus\n\nUnterlagen\nKalender\nStift\n\nKleidung\nUnterwäsche\nHemd\n\nZahnbürste\nKulturbeutel\n\nMedikamente\nRegenschirm"),
            Preset(id: "gym", name: "Fitness", detail: "Auf zum Training",
                   palette: Palette(6), columns: .four,
                   text: "Sportshirt\nShorts\nSocken\n\nSportschuhe\nHandtuch\nWechselkleidung\n\nTrinkflasche\nProtein\n\nMitgliedskarte\nSpindschlüssel\n\nShampoo\nDuschgel"),
            Preset(id: "camp", name: "Camping & Grillen", detail: "Draußen kochen",
                   palette: Palette(7), columns: .four,
                   text: "Zelt\nHeringe\nHammer\n\nSchlafsack\nIsomatte\nLaterne\n\nKocher\nHolzkohle\nAnzünder\nGrillzange\n\nKühlbox\nLebensmittel\nGetränke\n\nGeschirr\nBesteck\nGewürze\n\nArbeitshandschuhe\nMüllbeutel\nMückenspray"),
            Preset(id: "onsen", name: "Therme & Bad", detail: "Zum Baden gehen",
                   palette: Palette(8), columns: .four,
                   text: "Handtuch\nBadetuch\nWechselkleidung\n\nUnterwäsche\nSocken\n\nShampoo\nGesichtsreiniger\nGesichtswasser\n\nHaargummi\nKleingeld\nGetränk"),
            Preset(id: "kids", name: "Mit Kindern raus", detail: "Mit den Kleinen unterwegs",
                   palette: Palette(9), columns: .four,
                   text: "Windeln\nFeuchttücher\nPlastiktüten\n\nWechselkleidung\nLätzchen\nHandtuch\n\nMilchpulver\nFläschchen\nWasser\n\nSnacks\nSpielzeug\nBilderbuch\n\nImpfpass\nVersichertenkarte\nArztkarte\n\nBabytrage\nSonnencreme\nMütze"),
            Preset(id: "hospital", name: "Arztbesuch", detail: "Zum Arzt gehen",
                   palette: Palette(10), columns: .four,
                   text: "Versichertenkarte\nArztkarte\nMedikamentenplan\n\nGeldbörse\nBargeld\nHandy\n\nÜberweisung\nBefunde\n\nMaske\nGetränk"),
            Preset(id: "ceremony", name: "Feierlichkeit", detail: "Hochzeiten und Trauerfeiern",
                   palette: Palette(4), columns: .four,
                   text: "Anzug\nKrawatte\nSchwarze Socken\n\nGeschenk\nKarte\nUmschlag\n\nTaschentuch\nStift\nPfefferminz\n\nGeldbörse\nHandy"),
            Preset(id: "disaster", name: "Notfallset", detail: "Inhalt des Notfallrucksacks",
                   palette: Palette(8), columns: .four,
                   text: "Wasser\nNotvorrat\nRadio\n\nTaschenlampe\nBatterien\nPowerbank\n\nErste-Hilfe-Set\nMedikamente\nMaske\n\nBargeld\nAusweiskopie\nBankkarte\n\nArbeitshandschuhe\nTrillerpfeife\nRegenjacke\n\nHandtuch\nZahnbürste\nNotfalltoilette"),
        ]
    }

    private static func it() -> [Preset] {
        [
            Preset(id: "town", name: "In giro", detail: "Una breve uscita",
                   palette: Palette(1), columns: .four,
                   text: "Portafoglio\nTelefono\nChiavi\nFazzoletti\n\nAuricolari\nCaricatore\nPower bank\n\nCollirio\nBurrocacao\nMascherina"),
            Preset(id: "commute", name: "Pendolare", detail: "La borsa di ogni giorno",
                   palette: Palette(2), columns: .four,
                   text: "Portafoglio\nTelefono\nChiavi\nBadge\n\nAbbonamento\nBiglietto\n\nPortatile\nCaricatore\nAgenda\nPenna\n\nPranzo\nBorraccia\nOmbrello"),
            Preset(id: "trip-domestic", name: "Weekend fuori", detail: "Una o due notti",
                   palette: Palette(3), columns: .four,
                   text: "Portafoglio\nTelefono\nChiavi\nPatente\n\nVestiti\nIntimo\nCalzini\nPigiama\n\nSpazzolino\nDetergente viso\nTrucchi\nAsciugamano\n\nCaricatore\nPower bank\nAuricolari\n\nMedicine\nCerotti\nMascherina\n\nBorsa di tela\nSacchetti"),
            Preset(id: "trip-abroad", name: "Viaggio all'estero", detail: "Ciò che lì non trovi",
                   palette: Palette(4), columns: .four,
                   text: "Passaporto\nBiglietti aerei\nPortafoglio\nContanti\n\nCarta di credito\nAssicurazione\neSIM\n\nAdattatore\nCaricatore\nPower bank\n\nVestiti\nIntimo\nCalzini\nGiacca\n\nSpazzolino\nBeauty case\nTrucchi\n\nMedicine\nAntinausea\nMascherina\n\nBenda occhi\nTappi orecchie\nCuscino collo"),
            Preset(id: "business", name: "Trasferta", detail: "Una notte per lavoro",
                   palette: Palette(5), columns: .four,
                   text: "Portafoglio\nTelefono\nBadge\nBiglietti visita\n\nPortatile\nCaricatore\nMouse\n\nDocumenti\nAgenda\nPenna\n\nVestiti\nIntimo\nCamicia\n\nSpazzolino\nBeauty case\n\nMedicine\nOmbrello"),
            Preset(id: "gym", name: "Palestra", detail: "Per andare ad allenarsi",
                   palette: Palette(6), columns: .four,
                   text: "Maglietta\nPantaloncini\nCalzini\n\nScarpe\nAsciugamano\nCambio\n\nBorraccia\nProteine\n\nTessera\nChiave armadietto\n\nShampoo\nBagnoschiuma"),
            Preset(id: "camp", name: "Campeggio e grigliata", detail: "Cucinare all'aperto",
                   palette: Palette(7), columns: .four,
                   text: "Tenda\nPicchetti\nMartello\n\nSacco a pelo\nMaterassino\nLanterna\n\nFornellino\nCarbonella\nAccendifuoco\nPinze\n\nFrigo portatile\nCibo\nBevande\n\nStoviglie\nPosate\nCondimenti\n\nGuanti\nSacchi rifiuti\nAntizanzare"),
            Preset(id: "onsen", name: "Terme", detail: "Per andare a fare il bagno",
                   palette: Palette(8), columns: .four,
                   text: "Asciugamano\nTelo bagno\nCambio\n\nIntimo\nCalzini\n\nShampoo\nDetergente viso\nTonico\n\nElastico\nMonete\nBevanda"),
            Preset(id: "kids", name: "Uscita con i bimbi", detail: "Con i più piccoli",
                   palette: Palette(9), columns: .four,
                   text: "Pannolini\nSalviette\nSacchetti\n\nCambio\nBavaglino\nAsciugamano\n\nLatte in polvere\nBiberon\nAcqua\n\nMerenda\nGiocattoli\nLibro illustrato\n\nLibretto sanitario\nTessera sanitaria\nTessera clinica\n\nMarsupio\nCrema solare\nCappellino"),
            Preset(id: "hospital", name: "Visita medica", detail: "Per andare dal medico",
                   palette: Palette(10), columns: .four,
                   text: "Tessera sanitaria\nTessera clinica\nElenco farmaci\n\nPortafoglio\nContanti\nTelefono\n\nImpegnativa\nReferti\n\nMascherina\nBevanda"),
            Preset(id: "ceremony", name: "Cerimonia", detail: "Matrimoni e funerali",
                   palette: Palette(4), columns: .four,
                   text: "Abito\nCravatta\nCalzini neri\n\nRegalo\nBiglietto\nBusta\n\nFazzoletto\nPenna\nMentine\n\nPortafoglio\nTelefono"),
            Preset(id: "disaster", name: "Kit di emergenza", detail: "Cosa mettere nello zaino",
                   palette: Palette(8), columns: .four,
                   text: "Acqua\nScorte\nRadio\n\nTorcia\nBatterie\nPower bank\n\nKit pronto soccorso\nMedicine\nMascherina\n\nContanti\nCopia documento\nBancomat\n\nGuanti\nFischietto\nImpermeabile\n\nAsciugamano\nSpazzolino\nWC portatile"),
        ]
    }

    private static func ptBR() -> [Preset] {
        [
            Preset(id: "town", name: "Saindo", detail: "Uma saída rápida",
                   palette: Palette(1), columns: .four,
                   text: "Carteira\nCelular\nChaves\nLenços\n\nFones\nCarregador\nPower bank\n\nColírio\nProtetor labial\nMáscara"),
            Preset(id: "commute", name: "Trabalho", detail: "A bolsa do dia a dia",
                   palette: Palette(2), columns: .four,
                   text: "Carteira\nCelular\nChaves\nCrachá\n\nBilhete único\nCartão transporte\n\nNotebook\nCarregador\nAgenda\nCaneta\n\nMarmita\nGarrafa de água\nGuarda-chuva"),
            Preset(id: "trip-domestic", name: "Viagem curta", detail: "Uma ou duas noites fora",
                   palette: Palette(3), columns: .four,
                   text: "Carteira\nCelular\nChaves\nCNH\n\nRoupas\nRoupa íntima\nMeias\nPijama\n\nEscova de dentes\nSabonete facial\nMaquiagem\nToalha\n\nCarregador\nPower bank\nFones\n\nRemédios\nCurativos\nMáscara\n\nEcobag\nSacolas"),
            Preset(id: "trip-abroad", name: "Viagem ao exterior", detail: "O que não dá para comprar lá",
                   palette: Palette(4), columns: .four,
                   text: "Passaporte\nPassagens\nCarteira\nDinheiro\n\nCartão de crédito\nSeguro viagem\neSIM\n\nAdaptador\nCarregador\nPower bank\n\nRoupas\nRoupa íntima\nMeias\nCasaco\n\nEscova de dentes\nNécessaire\nMaquiagem\n\nRemédios\nAntienjoo\nMáscara\n\nTapa-olho\nProtetor auricular\nTravesseiro"),
            Preset(id: "business", name: "Viagem a trabalho", detail: "Uma noite a trabalho",
                   palette: Palette(5), columns: .four,
                   text: "Carteira\nCelular\nCrachá\nCartões de visita\n\nNotebook\nCarregador\nMouse\n\nDocumentos\nAgenda\nCaneta\n\nRoupas\nRoupa íntima\nCamisa social\n\nEscova de dentes\nNécessaire\n\nRemédios\nGuarda-chuva"),
            Preset(id: "gym", name: "Academia", detail: "Para ir treinar",
                   palette: Palette(6), columns: .four,
                   text: "Camiseta\nShort\nMeias\n\nTênis\nToalha\nTroca de roupa\n\nGarrafa de água\nWhey\n\nCarteirinha\nChave do armário\n\nXampu\nSabonete líquido"),
            Preset(id: "camp", name: "Camping e churrasco", detail: "Cozinhar ao ar livre",
                   palette: Palette(7), columns: .four,
                   text: "Barraca\nEstacas\nMartelo\n\nSaco de dormir\nIsolante\nLanterna\n\nFogareiro\nCarvão\nAcendedor\nPegador\n\nCooler\nComida\nBebidas\n\nPratos\nTalheres\nTemperos\n\nLuvas\nSacos de lixo\nRepelente"),
            Preset(id: "onsen", name: "Banho termal", detail: "Para ir tomar banho",
                   palette: Palette(8), columns: .four,
                   text: "Toalha\nToalha de banho\nTroca de roupa\n\nRoupa íntima\nMeias\n\nXampu\nSabonete facial\nTônico\n\nElástico\nMoedas\nBebida"),
            Preset(id: "kids", name: "Passeio com crianças", detail: "Levando os pequenos",
                   palette: Palette(9), columns: .four,
                   text: "Fraldas\nLenço umedecido\nSacolas\n\nTroca de roupa\nBabador\nToalha\n\nLeite em pó\nMamadeira\nÁgua\n\nLanche\nBrinquedos\nLivrinho\n\nCaderneta\nCarteirinha\nCartão SUS\n\nCanguru\nProtetor solar\nChapéu"),
            Preset(id: "hospital", name: "Consulta médica", detail: "Para ir ao médico",
                   palette: Palette(10), columns: .four,
                   text: "Carteirinha\nCartão SUS\nLista de remédios\n\nCarteira\nDinheiro\nCelular\n\nEncaminhamento\nExames\n\nMáscara\nBebida"),
            Preset(id: "ceremony", name: "Evento formal", detail: "Casamentos e velórios",
                   palette: Palette(4), columns: .four,
                   text: "Terno\nGravata\nMeias pretas\n\nPresente\nCartão\nEnvelope\n\nLenço\nCaneta\nBalas\n\nCarteira\nCelular"),
            Preset(id: "disaster", name: "Kit de emergência", detail: "O que vai na mochila",
                   palette: Palette(8), columns: .four,
                   text: "Água\nMantimentos\nRádio\n\nLanterna\nPilhas\nPower bank\n\nPrimeiros socorros\nRemédios\nMáscara\n\nDinheiro\nCópia do RG\nCartão do banco\n\nLuvas\nApito\nCapa de chuva\n\nToalha\nEscova de dentes\nBanheiro portátil"),
        ]
    }

    private static func ru() -> [Preset] {
        [
            Preset(id: "town", name: "Выйти из дома", detail: "Ненадолго по делам",
                   palette: Palette(1), columns: .four,
                   text: "Кошелёк\nТелефон\nКлючи\nСалфетки\n\nНаушники\nЗарядка\nПауэрбанк\n\nГлазные капли\nГигиеничка\nМаска"),
            Preset(id: "commute", name: "На работу", detail: "Сумка на каждый день",
                   palette: Palette(2), columns: .four,
                   text: "Кошелёк\nТелефон\nКлючи\nПропуск\n\nПроездной\nТранспортная карта\n\nНоутбук\nЗарядка\nЕжедневник\nРучка\n\nОбед\nБутылка воды\nЗонт"),
            Preset(id: "trip-domestic", name: "Поездка на выходные", detail: "На одну-две ночи",
                   palette: Palette(3), columns: .four,
                   text: "Кошелёк\nТелефон\nКлючи\nПрава\n\nОдежда\nБельё\nНоски\nПижама\n\nЗубная щётка\nПенка для лица\nКосметика\nПолотенце\n\nЗарядка\nПауэрбанк\nНаушники\n\nЛекарства\nПластыри\nМаска\n\nШопер\nПакеты"),
            Preset(id: "trip-abroad", name: "Поездка за границу", detail: "То, что там не купить",
                   palette: Palette(4), columns: .four,
                   text: "Паспорт\nБилеты\nКошелёк\nНаличные\n\nКредитка\nСтраховка\neSIM\n\nПереходник\nЗарядка\nПауэрбанк\n\nОдежда\nБельё\nНоски\nКуртка\n\nЗубная щётка\nКосметичка\nКосметика\n\nЛекарства\nОт укачивания\nМаска\n\nМаска для сна\nБеруши\nПодушка для шеи"),
            Preset(id: "business", name: "Командировка", detail: "Одна ночь по работе",
                   palette: Palette(5), columns: .four,
                   text: "Кошелёк\nТелефон\nПропуск\nВизитки\n\nНоутбук\nЗарядка\nМышь\n\nДокументы\nЕжедневник\nРучка\n\nОдежда\nБельё\nРубашка\n\nЗубная щётка\nКосметичка\n\nЛекарства\nЗонт"),
            Preset(id: "gym", name: "Спортзал", detail: "На тренировку",
                   palette: Palette(6), columns: .four,
                   text: "Футболка\nШорты\nНоски\n\nКроссовки\nПолотенце\nСменная одежда\n\nБутылка воды\nПротеин\n\nКлубная карта\nКлюч от шкафчика\n\nШампунь\nГель для душа"),
            Preset(id: "camp", name: "Кемпинг и шашлыки", detail: "Готовим на природе",
                   palette: Palette(7), columns: .four,
                   text: "Палатка\nКолышки\nМолоток\n\nСпальник\nКоврик\nФонарь\n\nГорелка\nУголь\nРозжиг\nЩипцы\n\nТермосумка\nПродукты\nНапитки\n\nПосуда\nПриборы\nСпеции\n\nПерчатки\nМешки для мусора\nРепеллент"),
            Preset(id: "onsen", name: "Баня и сауна", detail: "Когда идёшь попариться",
                   palette: Palette(8), columns: .four,
                   text: "Полотенце\nБанное полотенце\nСменная одежда\n\nБельё\nНоски\n\nШампунь\nПенка для лица\nТоник\n\nРезинка\nМелочь\nНапиток"),
            Preset(id: "kids", name: "С детьми", detail: "Когда берёшь малышей",
                   palette: Palette(9), columns: .four,
                   text: "Подгузники\nСалфетки\nПакеты\n\nСменная одежда\nСлюнявчик\nПолотенце\n\nСмесь\nБутылочка\nВода\n\nПерекус\nИгрушки\nКнижка\n\nМедкарта\nПолис ОМС\nКарта клиники\n\nСлинг\nСолнцезащитный\nПанамка"),
            Preset(id: "hospital", name: "К врачу", detail: "Когда идёшь в поликлинику",
                   palette: Palette(10), columns: .four,
                   text: "Полис ОМС\nКарта клиники\nСписок лекарств\n\nКошелёк\nНаличные\nТелефон\n\nНаправление\nАнализы\n\nМаска\nНапиток"),
            Preset(id: "ceremony", name: "Торжество", detail: "Свадьбы и похороны",
                   palette: Palette(4), columns: .four,
                   text: "Костюм\nГалстук\nЧёрные носки\n\nПодарок\nОткрытка\nКонверт\n\nПлаток\nРучка\nМятные конфеты\n\nКошелёк\nТелефон"),
            Preset(id: "disaster", name: "Тревожный чемоданчик", detail: "Что положить в сумку",
                   palette: Palette(8), columns: .four,
                   text: "Вода\nСухпаёк\nРадио\n\nФонарик\nБатарейки\nПауэрбанк\n\nАптечка\nЛекарства\nМаска\n\nНаличные\nКопия паспорта\nБанковская карта\n\nПерчатки\nСвисток\nДождевик\n\nПолотенце\nЗубная щётка\nБиотуалет"),
        ]
    }

    private static func ar() -> [Preset] {
        [
            Preset(id: "town", name: "الخروج", detail: "مشوار قصير",
                   palette: Palette(1), columns: .four,
                   text: "المحفظة\nالهاتف\nالمفاتيح\nمناديل\n\nسماعات\nالشاحن\nباور بنك\n\nقطرة العين\nمرطب شفاه\nكمامة"),
            Preset(id: "commute", name: "الذهاب للعمل", detail: "حقيبتك اليومية",
                   palette: Palette(2), columns: .four,
                   text: "المحفظة\nالهاتف\nالمفاتيح\nبطاقة العمل\n\nاشتراك المواصلات\nبطاقة المترو\n\nلابتوب\nالشاحن\nمفكرة\nقلم\n\nالغداء\nزجاجة ماء\nمظلة"),
            Preset(id: "trip-domestic", name: "رحلة قصيرة", detail: "ليلة أو ليلتان",
                   palette: Palette(3), columns: .four,
                   text: "المحفظة\nالهاتف\nالمفاتيح\nرخصة القيادة\n\nملابس\nملابس داخلية\nجوارب\nبيجامة\n\nفرشاة أسنان\nغسول الوجه\nمستحضرات تجميل\nمنشفة\n\nالشاحن\nباور بنك\nسماعات\n\nأدوية\nلاصقات جروح\nكمامة\n\nحقيبة قماش\nأكياس بلاستيك"),
            Preset(id: "trip-abroad", name: "سفر للخارج", detail: "ما لا تجده هناك",
                   palette: Palette(4), columns: .four,
                   text: "جواز السفر\nالتذاكر\nالمحفظة\nنقود\n\nبطاقة ائتمان\nتأمين السفر\neSIM\n\nمحول قابس\nالشاحن\nباور بنك\n\nملابس\nملابس داخلية\nجوارب\nسترة\n\nفرشاة أسنان\nأدوات الحمام\nمستحضرات تجميل\n\nأدوية\nدواء دوار الحركة\nكمامة\n\nقناع النوم\nسدادات أذن\nوسادة رقبة"),
            Preset(id: "business", name: "رحلة عمل", detail: "ليلة واحدة للعمل",
                   palette: Palette(5), columns: .four,
                   text: "المحفظة\nالهاتف\nبطاقة العمل\nبطاقات تعريف\n\nلابتوب\nالشاحن\nفأرة\n\nمستندات\nمفكرة\nقلم\n\nملابس\nملابس داخلية\nقميص\n\nفرشاة أسنان\nأدوات الحمام\n\nأدوية\nمظلة"),
            Preset(id: "gym", name: "النادي الرياضي", detail: "للذهاب إلى التمرين",
                   palette: Palette(6), columns: .four,
                   text: "ملابس رياضية\nشورت\nجوارب\n\nحذاء رياضي\nمنشفة\nملابس بديلة\n\nزجاجة ماء\nبروتين\n\nبطاقة العضوية\nمفتاح الخزانة\n\nشامبو\nغسول الجسم"),
            Preset(id: "camp", name: "تخييم وشواء", detail: "الطبخ في الهواء الطلق",
                   palette: Palette(7), columns: .four,
                   text: "خيمة\nأوتاد\nمطرقة\n\nكيس النوم\nحصيرة\nفانوس\n\nموقد\nفحم\nمشعل النار\nملقط\n\nصندوق تبريد\nطعام\nمشروبات\n\nأطباق\nأدوات المائدة\nتوابل\n\nقفازات\nأكياس قمامة\nطارد الحشرات"),
            Preset(id: "onsen", name: "حمام عام", detail: "للذهاب إلى الاستحمام",
                   palette: Palette(8), columns: .four,
                   text: "منشفة\nمنشفة حمام\nملابس بديلة\n\nملابس داخلية\nجوارب\n\nشامبو\nغسول الوجه\nتونر\n\nربطة شعر\nفكة\nمشروب"),
            Preset(id: "kids", name: "خروج مع الأطفال", detail: "مع الصغار",
                   palette: Palette(9), columns: .four,
                   text: "حفاضات\nمناديل مبللة\nأكياس بلاستيك\n\nملابس بديلة\nمريلة\nمنشفة\n\nحليب أطفال\nرضاعة\nماء\n\nوجبات خفيفة\nألعاب\nكتاب مصور\n\nسجل الصحة\nبطاقة التأمين\nبطاقة العيادة\n\nحمالة الطفل\nواقي الشمس\nقبعة"),
            Preset(id: "hospital", name: "زيارة الطبيب", detail: "للذهاب إلى العيادة",
                   palette: Palette(10), columns: .four,
                   text: "بطاقة التأمين\nبطاقة العيادة\nقائمة الأدوية\n\nالمحفظة\nنقود\nالهاتف\n\nخطاب التحويل\nنتائج الفحص\n\nكمامة\nمشروب"),
            Preset(id: "ceremony", name: "مناسبة رسمية", detail: "الأعراس والعزاء",
                   palette: Palette(4), columns: .four,
                   text: "بدلة\nربطة عنق\nجوارب سوداء\n\nهدية\nبطاقة\nظرف\n\nمنديل\nقلم\nحلوى نعناع\n\nالمحفظة\nالهاتف"),
            Preset(id: "disaster", name: "حقيبة الطوارئ", detail: "ما يوضع في حقيبة الإخلاء",
                   palette: Palette(8), columns: .four,
                   text: "ماء\nطعام الطوارئ\nراديو\n\nمصباح يدوي\nبطاريات\nباور بنك\n\nحقيبة إسعاف\nأدوية\nكمامة\n\nنقود\nنسخة الهوية\nبطاقة بنكية\n\nقفازات\nصفارة\nمعطف مطر\n\nمنشفة\nفرشاة أسنان\nمرحاض محمول"),
        ]
    }
}

extension CoreText {
    static let table: [Key: [Language: String]] = [
        .untitledList: [.ja: "名前のないリスト", .en: "Untitled list", .zhHans: "未命名列表", .zhHant: "未命名清單", .ko: "이름 없는 목록", .es: "Lista sin nombre", .fr: "Liste sans nom", .de: "Unbenannte Liste", .it: "Elenco senza nome", .ptBR: "Lista sem nome", .ru: "Список без названия", .ar: "قائمة بلا اسم"],
        .newList: [.ja: "新しいリスト", .en: "New list", .zhHans: "新列表", .zhHant: "新清單", .ko: "새 목록", .es: "Lista nueva", .fr: "Nouvelle liste", .de: "Neue Liste", .it: "Nuovo elenco", .ptBR: "Nova lista", .ru: "Новый список", .ar: "قائمة جديدة"],
        .copyOf: [.ja: "%@のコピー", .en: "%@ copy", .zhHans: "%@ 副本", .zhHant: "%@ 副本", .ko: "%@ 사본", .es: "%@ (copia)", .fr: "%@ (copie)", .de: "%@ (Kopie)", .it: "%@ (copia)", .ptBR: "%@ (cópia)", .ru: "%@ (копия)", .ar: "%@ (نسخة)"],
        .copyOfNumbered: [.ja: "%@のコピー%lld", .en: "%@ copy %lld", .zhHans: "%@ 副本 %lld", .zhHant: "%@ 副本 %lld", .ko: "%@ 사본 %lld", .es: "%@ (copia %lld)", .fr: "%@ (copie %lld)", .de: "%@ (Kopie %lld)", .it: "%@ (copia %lld)", .ptBR: "%@ (cópia %lld)", .ru: "%@ (копия %lld)", .ar: "%@ (نسخة %lld)"],
        .appearanceSystem: [.ja: "自動", .en: "Automatic", .zhHans: "自动", .zhHant: "自動", .ko: "자동", .es: "Automático", .fr: "Automatique", .de: "Automatisch", .it: "Automatico", .ptBR: "Automático", .ru: "Авто", .ar: "تلقائي"],
        .appearanceLight: [.ja: "ライト", .en: "Light", .zhHans: "浅色", .zhHant: "淺色", .ko: "라이트", .es: "Claro", .fr: "Clair", .de: "Hell", .it: "Chiaro", .ptBR: "Claro", .ru: "Светлая", .ar: "فاتح"],
        .appearanceDark: [.ja: "ダーク", .en: "Dark", .zhHans: "深色", .zhHant: "深色", .ko: "다크", .es: "Oscuro", .fr: "Sombre", .de: "Dunkel", .it: "Scuro", .ptBR: "Escuro", .ru: "Тёмная", .ar: "داكن"],
    ]
}
